module 03
js-tasks-ru/htmlcss-20210114_dm-sudin pull request #3
Opened 2021-02-06 14:28 UTC by dm-sudin

2021-02-13 12:21 UTC, PDmitryA requested changes
еще вернусь сегодня)

2021-02-13 12:21 UTC, PDmitryA commented on 03-lection1/02-accordion/accordion.css
> +.container {
по структуре 1 файл = 1 бэм блок.
это нужно, чтобы файлы из задачек мы смогли подключить на страницу проекта и классы, объявленные в них не влияли на другие компоненты.

если нужно какие-то стили вынести для демонстрационной странички аккордеона / любого другого компонента, то давай их унесем либо в тег `style` либо в css-файлик рядом, который в дальнейшем в проект подключать не будем.

2021-02-13 12:21 UTC, PDmitryA commented on 03-lection1/02-accordion/accordion.css
> +.marker {
кажется, маркер не будет никогда использоваться отдельно от аккордеона. давай сделаем его элементом? тем более, что между ними есть связь в состоянии "open".

2021-02-13 12:21 UTC, PDmitryA commented on 03-lection1/02-accordion/accordion.css
> +    position:absolute;
лучше бы стрелку не вырывать из нормального потока. введи длинный заголовок в summary - он залезет под стрелочку.

2021-02-13 12:21 UTC, PDmitryA commented on 05-lection3/02-modal/modal.css
> +body {
тоже вынести либо в тег `style` либо в файл рядом

2021-02-13 12:21 UTC, PDmitryA commented on 05-lection3/02-modal/modal.css
> +#modal-close {
несмотря на то, что js в нашем случае привязан к id, стилизацию нужно также, как и для всех других элементов блока модалки, делать через классы

2021-02-13 12:21 UTC, PDmitryA commented on 05-lection3/02-modal/modal.css
> +#modal-close {
то же самое про #modal

2021-02-13 12:21 UTC, PDmitryA commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_beetwin {
between

2021-02-13 12:21 UTC, PDmitryA commented on 05-lection3/03-calendar/calendar.css
> +* {
осталось от разработки

2021-02-13 12:21 UTC, PDmitryA commented on 06-lection4/02-background-image/background-image.css
> +        background-size: cover;
повторяющиеся можно вынести, а в целом задачка ок

2021-02-13 12:21 UTC, PDmitryA commented on assets/css/main.css
> +    --text-calendar-main: #334D6E;
норм, с таким обычно нужно идти к дизайнеру и говорить, что что-то тут не так.
можешь взять любой из общих цветов, или оставить так - на твой вкус)

2021-02-13 12:21 UTC, PDmitryA commented on assets/css/main.css
> +    --touch-width: 468px;
тру, подняли эту тему в чате.
договорились, что эти контрольные значения после лекции про адаптив подставляем просто в своих абсолютных величинах.
при выполнении дз после лекции про сборку scss -> css определяем их как scss-переменные

2021-02-13 12:21 UTC, PDmitryA commented on assets/css/main.css
>  * {
еще я бы рекомендовал сделать несколько файлов рядом - `variables.css`, `custom-reset.css`, а в main только импортировать)
не обязательно, только ради удобства

2021-02-13 12:21 UTC, PDmitryA commented on assets/images/cross.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
кажется, стало лишним после внедрения спрайтов

2021-02-13 12:22 UTC, PDmitryA commented
пока что компоненты вживую не смотрел, только по коду

2021-02-13 20:07 UTC, dm-sudin commented on assets/images/cross.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
поправил

2021-02-23 09:01 UTC, PDmitryA requested changes
не смог запустить проект. как ты его собираешь?

про переменные коммент оставил

2021-02-23 09:01 UTC, PDmitryA commented on assets/css/variables.scss
> +    $white: #FFFFFF;
не нужно все переменные переводить в scss. оставь их css-переменными на :root.
scss-переменными должны быть только размеры экрана.

2021-02-23 09:28 UTC, PDmitryA commented
кнопка - ок
аккордеон - ок. есть минорное замечание - область клика не. cursor: pointer и довольно маленькая сама по себе.
гистограмма - разломана css-переменными
скелетон - css-переменные
тултип - баг - когда навожу на область svg , то тултип становится видимым. нужно задать svg width, height
модалка - ок
календарь - ок
аватарка - ок
background-image - ок
srcset - ок
общее замечание по контролам форм - при табуляции текст должен подчеркиваться. minor.
чекбокс - ок
радио - ок
тогглер - ок
input - empty и focus хорошо бы обработать с помощью css. success и invalid отдельными классами, да.

2021-02-23 09:29 UTC, PDmitryA commented
> не смог запустить проект. как ты его собираешь?

точнее хотел сказать, что переменные не проросли на главную страницу и страницу компонента.

2021-02-25 22:02 UTC, PDmitryA commented
то, что есть, по итогу мержу.

2021-02-25 22:02 UTC, merged